prefix skos: <http://www.w3.org/2004/02/skos/core#>

select ?label ?widerLabel
where 
{
?concept a skos:Concept ;
      (skos:prefLabel|skos:altLabel) ?label ;
      skos:broader+ ?broader .
?broader (skos:prefLabel|skos:altLabel) ?widerLabel .
}
